### ISSUE TITLE
Nothing appears in the settings layout

### ISSUE THREAD

**Issue by JLBA** [Kreativsoehne/Cookieconsent#1]
Hello,
I'm just trying cookieconsent in a Contao 4.4 installation. 
I've created the 3 minimal categories. 
I have created one cookie : PHPSESSID in the category Necessery.

The first message is displayed correctly. But when clicking on Settings, the second layer is displayed with only the two buttons. No categories, no cookie to check. 
I'm missing something but what ?
Thanks for your help.

**Comment by Songworks** [comment]
Hi there,

ok, I'll have a look at it and see if I can reproduce it.
Could you please check if you get any Javascript errors in your browsers console?

Thanks!

**Comment by JLBA** [comment]
Thanks for your answer.
I just created a test version of my site : http://terea3test.lestock.net/. I can give you access to the BE.
I have added your dump. Categories and cookies are well displayed on the FE.
I manually added mystestcookie in Necessary cat. but it is not displayed. Except it is in Mysql table. A bit strange...

And to answer to you, I don't see javascript spécific message in the console.

But there is a strange white space in BE cookie/service :
![kreative_ cc - cookie](https://user-images.githubusercontent.com/2730432/137604169-161c053a-2466-4010-b303-a538c3350cc7.png)

**Comment by JLBA** [comment]
![kreative_ cc - cookie](https://user-images.githubusercontent.com/2730432/137604165-ed5820c3-30bc-4851-a62c-302cb2f89400.png)

**Comment by Songworks** [comment]
Oh yeah, the space you've pointed out should contain the fields and options to add/edit the cookies languages (Name and Description basically).
That's probably the problem too. If it doesn't have a proper name and/or description the Javascript won't or can't render the cookie.
Hmm, probably a compatability issue with Contao 4.4, I haven't tried backend editing with 4.4 in a while...

**Comment by Songworks** [comment]
Hi there,
if you are still interested: I pushed a new version 3.1.1, which should fix the issue with missing backend settings described in your last [comment](https://github.com/Kreativsoehne/Cookieconsent/issues/1#issuecomment-945017884).

As those language settings are necessary for rendering the consent layer in frontend, then this should fix the original issue also.

Cheers!

**Comment by JLBA** [comment]
This works. Thank you. How can I help you translating in french ?
